<font size = "+3"> Tablice NumPy </font>

W tym notebooku omówimy:
- Tworzenie tablic (1D, 2D, 3D)
- Atrybuty tablic NumPy: shape, len, ndim, dtype, astype, size, axis
- Indeksowanie i dzielenie tablicy (slicing)
- Manipulacja tablicy
- Zmiana rozmiaru, przekształcanie, dołączanie, usuwanie, wstawianie

Zrozumiemy wspólną notację tablic NumPy w całym notebooku:
- Tablica 1D: Zastosowana notacja to arr1D
- Tablica 2D: Zastosowana notacja to arr2D
- Tablica 3D: Zastosowana notacja to arr3D

## Utworzenie tablicy NumPy

In [ ]:
# Zaimportuj bibliotekę NumPy
import numpy as np

In [ ]:
# Dodawanie audio, obrazu i wideo YouTube w notebooku Jupyter
from IPython.display import Audio,Image,YouTubeVideo

### Tablica 1D (jednowymiarową – 1 dimension)

In [ ]:
# Zaimportuj bibliotekę NumPy
import numpy as np
# Utwórz tablicę 1D NumPy
arr1D = np.array([5, 8, 12])
print(arr1D)

[ 5  8 12]


### Tablica 2D (dwuwymiarową – 2 dimensions)

In [88]:
# Utwórz tablicę 2D
arr2D = np.array([[23,45,67],[78,65,92]])
print(arr2D)

[[23 45 67]
 [78 65 92]]


### Tablica 3D (trójwymiarową – 3 dimensions)

In [89]:
# Utwórz tablicę 3D
arr3D=np.array([[[2,17], [45, 78]], [[88, 92], [60, 76]],[[76,33],[20,18]]])
arr3D

array([[[ 2, 17],
        [45, 78]],

       [[88, 92],
        [60, 76]],

       [[76, 33],
        [20, 18]]])

**<p style = "font-family: arial; font-size: 1.4em; color: blue;">Ćwiczenie: Utwórz tablice NumPy</p>**

In [ ]:
# Ćwiczenie: Utwórz tablicę 1D


In [ ]:
# Ćwiczenie: Utwórz tablicę 2D


In [ ]:
# Ćwiczenie: Utwórz tablicę 3D


## Atrybuty tablicy NumPy

### Atrybut shape (kształt tablicy)

In [ ]:
# Tablica 1D
arr1D

array([ 5,  8, 12])

In [94]:
arr1Dshape=np.shape(arr1D)
arr1Dshape

(3,)

In [ ]:
# Tablica 2D
arr2D

array([[23, 45, 67],
       [78, 65, 92]])

In [96]:
arr2Dshape=np.shape(arr2D)
arr2Dshape

(2, 3)

In [ ]:
# Tablica 3D
arr3D=np.array([[[2,17], [45, 78]], [[88, 92], [60, 76]],[[76,33],[20,18]]])
arr3D

array([[[ 2, 17],
        [45, 78]],

       [[88, 92],
        [60, 76]],

       [[76, 33],
        [20, 18]]])

In [98]:
arr3Dshape=np.shape(arr3D)
arr3Dshape

(3, 2, 2)

### Atrybut - długość

In [ ]:
# Długość tablicy (len) – liczba elementów w pierwszym wymiarze
arr1D

array([ 5,  8, 12])

In [100]:
# Znajdź długość tablicy
print(len(arr1D))

3


In [ ]:
# Tablica 2D
arr2D

array([[23, 45, 67],
       [78, 65, 92]])

In [102]:
# Znajdź długość tablicy
print(len(arr2D))

2


In [ ]:
# Tablica 3D
arr3D

array([[[ 2, 17],
        [45, 78]],

       [[88, 92],
        [60, 76]],

       [[76, 33],
        [20, 18]]])

In [104]:
# Znajdź długość tablicy
print(len(arr3D))

3


### Atrybut - ndim (liczba wymiarów)

In [ ]:
# Liczba wymiarów tablicy (ndim)
arr1D

array([ 5,  8, 12])

In [ ]:
# Liczba wymiarów
print(arr1D.ndim)

1


In [ ]:
# Liczba wymiarów tablicy NumPy
# Tablica 2D
arr2D

array([[23, 45, 67],
       [78, 65, 92]])

In [ ]:
# Liczba wymiarów
print(arr2D.ndim)

2


In [ ]:
# Tablica 3D
arr3D

array([[[ 2, 17],
        [45, 78]],

       [[88, 92],
        [60, 76]],

       [[76, 33],
        [20, 18]]])

In [ ]:
# Liczba wymiarów
print(arr3D.ndim)

3


### Atrybut - dtype (typ danych)

In [ ]:
# Typ danych tablicy (dtype)
arr1D

array([ 5,  8, 12])

In [112]:
# Typ danych
print(arr1D.dtype)

int32


In [ ]:
# Tablica 1D - typ danych string
arr1Dnew=np.array(['Tom','Nick'])
arr1Dnew

array(['Tom', 'Nick'], dtype='<U4')

In [114]:
# Typ danych
print(arr1Dnew.dtype)

<U4


In [ ]:
# Tablica 2D
arr2D

array([[23, 45, 67],
       [78, 65, 92]])

In [116]:
# Typ danych
print(arr2D.dtype)

int32


In [ ]:
# Tablica 2D - typ danych complex
arr2Dnew = np.array([[1+2j,1+3j],[5+6j,3+8j]])
arr2Dnew

array([[1.+2.j, 1.+3.j],
       [5.+6.j, 3.+8.j]])

In [ ]:
# Tablica 2D
print(arr2Dnew.dtype)

complex128


In [ ]:
# Tablica 3D
arr3D

array([[[ 2, 17],
        [45, 78]],

       [[88, 92],
        [60, 76]],

       [[76, 33],
        [20, 18]]])

In [120]:
# Typ danych
print(arr3D.dtype)

int32


### Atrybut - astype

In [ ]:
# Metoda astype (zmiana typu danych tablicy)


- Przykład: Biorąc pod uwagę tablicę NumPy, której podstawowe dane są typu „int32". Zmień typ danych danego obiektu na „float64".

In [ ]:
# Utwórz tablicę NumPy
Astypearr1D = np.array([10, 20, 30, 40, 50])
# Wydrukuj tablicę
print(Astypearr1D)
print(Astypearr1D.dtype)

[10 20 30 40 50]
int32


In [ ]:
# Zmień typ danych na „float64"
Astypearr1D= Astypearr1D.astype('float64')
print(Astypearr1D)
print(Astypearr1D.dtype)

[10. 20. 30. 40. 50.]
float64


### Atrybut - rozmiar

In [ ]:
# Rozmiar tablicy (size)
arr1D

array([ 5,  8, 12])

In [125]:
# Rozmiar tablicy
print(arr1D.size)

3


In [ ]:
# Tablica 2D
arr2D

array([[23, 45, 67],
       [78, 65, 92]])

In [127]:
# Rozmiar tablicy
print(arr2D.size)

6


In [ ]:
# Tablica 3D
arr3D

array([[[ 2, 17],
        [45, 78]],

       [[88, 92],
        [60, 76]],

       [[76, 33],
        [20, 18]]])

In [129]:
# Rozmiar tablicy
print(arr3D.size)

12


**<p style = "font-family: arial; font-size: 1.4em; color: blue;">Ćwiczenie: Atrybuty NumPy</p>**

In [ ]:
# 1. Napisz program NumPy, aby utworzyć 2-wymiarową tablicę rozmiaru 2 x 3. Wyprowadź kształt, typ i typ danych tablicy.


In [ ]:
# 2. Utwórz tablicę NumPy ([20,30,40]), której podstawowe dane są typu „int32".
# Zmień typ danych danego obiektu na „complex128".


### Atrybut axis (oś tablicy)

## Indeksowanie i wycinanie tablic

In [ ]:
# Tablica 1D
arr1D

array([ 5,  8, 12])

In [132]:
# # Dostęp do elementów
arr1D[0]

5

In [133]:
# # Dostęp do elementów
arr1D[2]

12

In [ ]:
# Tablica 2D
arr2D

array([[23, 45, 67],
       [78, 65, 92]])

In [135]:
# # Dostęp do elementów
arr2D[0,0]

23

In [136]:
arr2D[0,1]

45

In [137]:
arr2D[0,2]

67

In [138]:
arr2D[1,0]

78

In [139]:
arr2D[1,1]

65

In [140]:
arr2D[1,2]

92

In [ ]:
# # Zastosujmy wycinanie do tablicy 1D
arrSlice=np.array([5, 8, 12, 19, 14, 13])
arrSlice

array([ 5,  8, 12, 19, 14, 13])

In [142]:
arrSlice[2:5]

array([12, 19, 14])

In [143]:
arrSlice[:4]

array([ 5,  8, 12, 19])

In [144]:
arrSlice[4:]

array([14, 13])

In [ ]:
# # Zastosujmy wycinanie do tablicy 2D
arr2D

array([[23, 45, 67],
       [78, 65, 92]])

In [146]:
arr2D[:1,:2]

array([[23, 45]])

In [147]:
arr2D[1:2]

array([[78, 65, 92]])

In [148]:
arr2D[0:2]

array([[23, 45, 67],
       [78, 65, 92]])

**<p style = "font-family: arial; font-size: 1.4em; color: blue;">Ćwiczenie: Indeksowanie i wycinanie NumPy</p>**

In [ ]:
# 1. Pobierz trzeci i czwarty element z następującej tablicy:
# ([1, 2, 3, 4])


In [ ]:
# 2. Pobierz element z pierwszego wiersza, druga kolumna z następującej tablicy 2D:
# ([[1,2,3,4,5], [6,7,8,9,10]])


In [ ]:
# 3. Pokrój elementy od indeksu 1 do indeksu 5 z następującej tablicy:
# arr = ([1, 2, 3, 4, 5, 6, 7])


In [ ]:
# 4. Pokrój elementy od indeksu 4 do końca tablicy:
# arr = ([31, 21, 53, 14, 85, 16, 27])


In [ ]:
# 5. Pokrój elementy od początku do indeksu 4 (nie włączając):
# arr = ([31, 21, 53, 14, 85, 16, 27])


## Manipulacja tablicy

### Rozmiar

In [ ]:
# Resize() tablicy:
arr2D

array([[23, 45, 67],
       [78, 65, 92]])

In [150]:
# Użyjmy zmiany rozmiaru tablicy
arr2D.resize(1,6)
arr2D

array([[23, 45, 67, 78, 65, 92]])

In [151]:
arr2D.resize(6,1)
arr2D

array([[23],
       [45],
       [67],
       [78],
       [65],
       [92]])

In [ ]:
# Tablica
arr2D

array([[23],
       [45],
       [67],
       [78],
       [65],
       [92]])

### Reshape

In [ ]:
# Przekształcenie tablicy (reshape)
arr2D.reshape(3,2)

array([[23, 45],
       [67, 78],
       [65, 92]])

In [154]:
arr2D.reshape(6,1)

array([[23],
       [45],
       [67],
       [78],
       [65],
       [92]])

In [155]:
arr2D.reshape(1,6)

array([[23, 45, 67, 78, 65, 92]])

In [156]:
arr2D

array([[23],
       [45],
       [67],
       [78],
       [65],
       [92]])

In [157]:
arr2D.reshape(2,3)

array([[23, 45, 67],
       [78, 65, 92]])

### Dołącz dane do tablicy NumPy

In [158]:
# Utwórzmy nową tablicę i spróbuj dołączyć dane do tablicy
AppendArray= np.array([[1,2,3],[4,5,6]]) 
AppendArray

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Dołączanie elementów do tablicy (append)
print(np.append(AppendArray,[7,8,9])) 

[1 2 3 4 5 6 7 8 9]


In [160]:
print (np.append(AppendArray, [[7,8,9]],axis = 0))    # elementy wzdłuż osi x


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print (np.append(AppendArray, [[5,5,5],[7,8,9]],axis = 1)) # elementy wzdłuż osi Y


[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


### Usuń dane z tablicy NumPy

In [162]:
# Utwórzmy nową tablicę i spróbuj usunąć dane
Deletearr2D = np.array([[23,45,67],[78,65,92]])
print(Deletearr2D)

[[23 45 67]
 [78 65 92]]


In [ ]:
# Usuwanie elementów z tablicy (delete)
object=[0,1]
Deletearr2D = np.delete(Deletearr2D,object)
Deletearr2D

array([67, 78, 65, 92])

### Wstaw dane do tablicy NumPy

In [164]:
# Utwórzmy nową tablicę i spróbuj wstawić dane
Insertarr2D = np.array([[23,45,67],[78,65,92]])
print(Insertarr2D)

[[23 45 67]
 [78 65 92]]


In [ ]:
# Wstawianie elementów do tablicy (insert)
Insertarr2D = np.insert(Insertarr2D, 1, 9, axis = 1)
Insertarr2D

array([[23,  9, 45, 67],
       [78,  9, 65, 92]])

In [166]:
Insertarr2D = np.insert(Insertarr2D, [1,2], 9, axis = 1)
Insertarr2D

array([[23,  9,  9,  9, 45, 67],
       [78,  9,  9,  9, 65, 92]])

In [167]:
arr2D

array([[23],
       [45],
       [67],
       [78],
       [65],
       [92]])

**<p style = "font-family: arial; font-size: 1.4em; color: blue;">Ćwiczenie: Manipulacja tablicy</p>**

In [ ]:
# 1. Konwertuj następującą tablicę 1D z 12 elementami na tablicę 2D:
# ([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])


In [ ]:
# 2. Dołącz elementy ([7,8,9]) wzdłuż osi = 0 dla danej tablicy = ([[1,2,3], [4,5,6]])


In [ ]:
# 3. Wstaw elementy ([11,13]) wzdłuż osi = 1 w tablicy ([[1,2], [3,4], [5,6]])
