<font size = "+3"> Podstawowe operacje na tablicach NumPy </font>

W tym notebooku omówimy:
- Operacje arytmetyczne w NumPy
- Operacje macierzowe w NumPy
- Operacje statystyczne w NumPy

## Sekcja 1: Operacje arytmetyczne w NumPy
### Metoda i operator dodawania

In [ ]:
# Importuj bibliotekę NumPy
import numpy as np

In [ ]:
# Utwórz dwie tablice tego samego rozmiaru i wymiarów
# Użyj funkcji add()
AddarrA=np.array([10,20,30,40])
AddarrB=np.array([1,2,3,4])
np.add(AddarrA,AddarrB)

array([11, 22, 33, 44])

In [ ]:
# NumPy - operator dodawania
AddarrA,AddarrB

(array([10, 20, 30, 40]), array([1, 2, 3, 4]))

In [ ]:
# Dodaj tablice za pomocą operatora „+”
AddarrA+AddarrB

array([11, 22, 33, 44])

### Metoda i operator odejmowania

In [ ]:
# Utwórz dwie tablice o tym samym rozmiarze i wymiarach
# Użyj funkcji subtract()
SubtractarrA=np.array([25,15,35,45])
SubtractarrB=np.array([10,6,11,18])
np.subtract(SubtractarrA,SubtractarrB)

array([15,  9, 24, 27])

In [ ]:
# NumPy - operator odejmowania
SubtractarrA,SubtractarrB

(array([25, 15, 35, 45]), array([10,  6, 11, 18]))

In [ ]:
# Odejmij tablice za pomocą operatora „-”
SubtractarrA-SubtractarrB

array([15,  9, 24, 27])

### Metoda i operator mnożenia

In [ ]:
# Utwórz dwie tablice o tym samym rozmiarze i wymiarach
# Użyj funkcji multiply()
MultiplyarrA=np.array([3,5,7,9,11])
MultiplyarrB=np.array([2,4,6,8,10])
np.multiply(MultiplyarrA,MultiplyarrB)

array([  6,  20,  42,  72, 110])

In [ ]:
# NumPy - operator mnożenia
MultiplyarrA,MultiplyarrB

(array([ 3,  5,  7,  9, 11]), array([ 2,  4,  6,  8, 10]))

In [ ]:
# Pomnóż dwie tablice za pomocą operatora „*”
MultiplyarrA*MultiplyarrB

array([  6,  20,  42,  72, 110])

### Metoda i operator dzielenia

In [ ]:
# Utwórz dwie tablice o tym samym rozmiarze i wymiarach
# Użyj funkcji divide()
DividearrA=np.array([10,15,27,39,51])
DividearrB=np.array([2,3,9,13,16])
np.divide(DividearrA,DividearrB)

array([5.    , 5.    , 3.    , 3.    , 3.1875])

In [ ]:
# NumPy - operator dzielenia
DividearrA,DividearrB

(array([10, 15, 27, 39, 51]), array([ 2,  3,  9, 13, 16]))

In [ ]:
# Podziel tablice za pomocą operatora "/"
DividearrA/DividearrB

array([5.    , 5.    , 3.    , 3.    , 3.1875])

<font size="+2"> Ćwiczenie: Operacje arytmetyczne </font>

In [ ]:
# 1. Za pomocą funkcji add() dodaj dwie tablice A = ([[2, -7, 5], [-6, 2, 0]]); B = ([[5, 8, -5], [3, 6, 9]])


In [ ]:
# 2. Za pomocą funkcji multiply() pomnóż dwie tablice A = ([[7, -7], [-6, 2]]); B = ([[2, 7], [5, 9]])


## Sekcja 2: Operacje macierzowe w NumPy
### Iloczyn skalarny - np.inner i np.dot
### Obie funkcje liczą iloczyn skalarny
Dla tablic jednowymiarowych (wektorów 1D) obie funkcje działają tak samo — wykonują iloczyn dwóch wektorów i sumują wyniki.

In [ ]:
# Wektory jako tablice 1D NumPy
# Utwórz dwa wektory
InnerarrA = np.array([1, 2, 3])
InnerarrB = np.array([4, 5, 6])
print(InnerarrA,InnerarrB)

[1 2 3] [4 5 6]


In [ ]:
# Oblicz iloczyn skalarny
np.inner(InnerarrA,InnerarrB)

np.int64(32)

In [ ]:
# Oblicz iloczyn DOT
np.dot(InnerarrA,InnerarrB)

np.int64(32)

### Dla tablic dwuwymiarowych (macierzy 2D) funkcje np.inner i np.dot działają inaczej.
### np.dot wykonuje mnożenie macierzy, a np.inner liczy iloczyny skalarne między wierszami.
- np.dot(A, B) — mnożenie macierzowe (wiersze × kolumny)<br>
Wykonuje standardowe mnożenie macierzy:<br>
wiersze z A mnożone są przez kolumny z B.<br>

- np.inner(A, B) — iloczyn wewnętrzny (wiersz–wiersz)<br>
Funkcja liczy iloczyn skalarny każdego wiersza A z każdym wierszem B.<br>
Można ją stosować tylko wtedy, gdy wiersze A i B mają tę samą długość<br>
(czyli liczba kolumn w A musi być równa liczbie kolumn w B).<br>

In [ ]:
# Macierze jako obiekty ndarray
DotarrA = np.array([[1, 2], [3, 4]])
DotarrB = np.array([[5, 6, 7], [8, 9, 10]])
print(DotarrA)

[[1 2]
 [3 4]]


In [ ]:
print(DotarrB)

[[ 5  6  7]
 [ 8  9 10]]


In [ ]:
# Zastosuj iloczyn DOT
np.dot(DotarrA,DotarrB)

array([[21, 24, 27],
       [47, 54, 61]])

In [ ]:
InnerarrA = [[1, 2],
          [3, 4]]

InnerarrB = [[10, 20],
          [30, 40]]
np.inner(InnerarrA,InnerarrB)

array([[ 50, 110],
       [110, 250]])

### Transpozycja macierzy <br>
Zamienia wiersze na kolumny (przestawia osie).

In [ ]:
# Utwórz tablicę
Newarr = np.array([[1, 2], [3, 4], [5, 6]])
Newarr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# Zastosuj transpozycję macierzy
np.transpose(Newarr)

array([[1, 3, 5],
       [2, 4, 6]])

<font size="+2"> Ćwiczenie: Operacje macierzowe </font>

In [ ]:
# 1. Znajdź iloczyn skalarny dwóch tablic: A = ([[1,2], [3,4]]), B = ([[11, 12], [13, 14]])


In [ ]:
# 2. Znajdź transpozycję tablicy ([[0, 2], [1, 3]])


## Sekcja 3: Operacje statystyczne w NumPy

### Średnia <br>
Oblicza średnią arytmetyczną elementów.

In [ ]:
# Utwórz tablicę
ArrMean = np.array([5,6,7])
ArrMean

array([5, 6, 7])

In [ ]:
# Średnia
print(np.mean(ArrMean))

6.0


### Mediana <br>
Zwraca wartość środkową po posortowaniu danych.

In [ ]:
# Utwórz tablicę
ArrMedian=np.array([5,6,7,10,1,100])
ArrMedian

array([  5,   6,   7,  10,   1, 100])

KROK 1: Posortowanie danych<br>
KROK 2: Wyznaczenie wartości środkowej. Tablica ma 6 elementów (liczba parzysta), więc mediana to: element → 6 i element → 7<br>
NumPy liczy średnią z tych dwóch: (6+7)/2=6.5<br>

In [ ]:
# Mediana
print(np.median(ArrMedian))

6.5


### Odchylenie standardowe - np.std() <br>
Mierzy rozrzut danych wokół średniej (jak bardzo dane są „rozsiane”).<br><br>
Odchylenie standardowe mówi, jak bardzo wartości są rozrzucone wokół średniej:<br>
małe odchylenie → dane są blisko średniej<br>
duże odchylenie → wartości są bardziej rozproszone<br>
<br>
Krok 1: Średnia<br>

(5+6+7)/3=6<br>
Krok 2: Różnice od średniej<br>

5 − 6 = −1<br>
6 − 6 = 0<br>
7 − 6 = 1<br>
Krok 3: Kwadraty różnic<br>

(−1)² = 1<br>
0² = 0<br>
1² = 1<br>
Krok 4: Średnia z kwadratów<br>

(1+0+1)/3=2/3≈0.6667<br>
Krok 5: Pierwiastek 0.6667 ≈ 0.81649658<br>

Wynik:<br>
np.std(ArrStdDev) = 0.81649658<br>

###Podsumowanie<br>

Funkcja np.std():<br>

✔ znajduje średnią<br>
✔ liczy różnice od średniej<br>
✔ podnosi je do kwadratu<br>
✔ uśrednia<br>
✔ wyciąga pierwiastek<br>

In [ ]:
# Utwórz tablicę
ArrStdDev=np.array([5,6,7])
ArrStdDev

array([5, 6, 7])

In [ ]:
# Odchylenie standardowe
print(np.std(ArrStdDev))

0.816496580927726


<font size="+2"> Ćwiczenie: Operacje statystyczne </font>

In [ ]:
# Znajdź średnią, medianę i odchylenie standardowe tablicy ([10,56,23,97])
